

export enum UserRole {
  CLIENT = 'Client',
  MANUFACTURER = 'Manufacturer',
  ADMIN = 'Administrator'
}

export interface User {
  id: string;
  name: string;
  role: UserRole;
  isActive?: boolean; 
}

export interface ProductItem {
  id: string;
  name: string;
  description: string;
  estimatedProductionTime: string;
  materials?: string[]; 
  capacityPerWeek?: string; 
}

export interface ProductionFacility {
  id: string;
  ownerId: string;
  name: string;
  location: string;
  city: string;
  contactInfo: string;
  productionLoad: number;
  productCategories: string[];
  products: ProductItem[];
  estimatedTravelTime?: string;
  generalTurnaroundTime?: string;
  certifications?: string[]; 
  images?: string[]; 
}

export interface Inquiry {
  id: string;
  clientId: string; 
  clientName: string; 
  productionFacilityId: string;
  productionFacilityName: string;
  message: string;
  timestamp: Date;
  status: 'New' | 'Viewed' | 'Responded';
  response?: string;
  isAutoGenerated?: boolean;
  originalDelegationRequestId?: string;
  turnkeyProjectId?: string; // Added for project marketplace inquiries
}

export interface SearchCriteria {
  query: string;
  productCategory: string;
  latitude?: number;
  longitude?: number;
  minLoad?: number;
  maxLoad?: number;
  certifications?: string[];
}

export interface NotificationItem {
  id: string;
  userId: string;
  message: string;
  type: 'new_inquiry' | 'inquiry_response' | 'new_user_registered' | 'facility_updated' | 'generic_admin_message' | 'new_delegation_request' | 'delegation_request_update' | 'admin_initiated_match_inquiry' | 'new_special_offer_viewed' | 'follow_up_offer_received' | 'turnkey_project_created' | 'turnkey_project_update';
  relatedEntityId?: string; // e.g., inquiryId, userId, facilityId, delegationRequestId, offerId, turnkeyProjectId
  relatedEntityName?: string; // e.g., clientName, facilityName, projectName
  timestamp: Date;
  isRead: boolean;
}

export interface FavoriteFacility {
  userId: string;
  facilityId: string;
  facilityName: string;
  addedAt: Date;
}

export interface Employee {
  id: string;
  facilityOwnerId: string;
  name: string;
  defaultHourlyRate: number;
}

export interface WorkLogEntry {
  id: string;
  facilityOwnerId: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  hoursWorked: number;
  hourlyRate: number;
  calculatedPay: number;
  workDescription?: string;
  createdAt: Date;
}

export interface ArchivedEmployee extends Employee {
  archivedAt: Date;
}

export interface ArchivedWorkLogEntry extends WorkLogEntry {
  archivedAt: Date;
}

export interface DelegationRequest {
  id: string;
  clientId?: string;
  clientName: string;
  searchCriteria: SearchCriteria;
  timestamp: Date;
  status: 'Новая' | 'В работе' | 'Предложения отправлены' | 'Выполнена' | 'Отменена';
  adminNotes?: string;
  contactEmail?: string;
  contactPhone?: string;
  contactTelegram?: string;
}

export interface SpecialOffer {
  id: string;
  facilityId: string;
  facilityOwnerId: string;
  facilityName: string;
  title: string;
  description: string;
  discountPercentage?: number;
  fixedDiscountAmount?: number;
  applicableServices?: string[]; // Names of services or product categories
  validFrom: string; // YYYY-MM-DD
  validUntil: string; // YYYY-MM-DD
  promoCode?: string;
  termsAndConditions?: string;
  imageUrl?: string;
  createdAt: Date;
  updatedAt: Date;
  isActive: boolean;
  viewCount: number;
}

export interface SpecialOfferViewLog {
  id: string;
  offerId: string;
  clientId: string;
  clientName: string;
  viewedAt: Date;
  followUpSent: boolean;
  followUpMessage?: string; // The message manufacturer sent as a follow up
}

// --- Turnkey Project Types ---
export interface ProjectStage {
  stage: number;
  name: string;
  description: string;
  requiredCategory: string;
  keywords: string[];
  selectedFacilityId?: string;
  selectedFacilityName?: string;
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  inquiryId?: string;
}

export interface TurnkeyProject {
  id: string;
  clientId?: string; // Optional for guest submissions
  clientName: string; // The name of the submitter (guest or registered client)
  productDescription: string;
  projectName: string;
  stages: ProjectStage[];
  status: 'processing_ai' | 'pending_review' | 'published' | 'in_progress' | 'completed' | 'cancelled'; // Added 'published'
  createdAt: Date;
  adminNotes?: string; // Added for potential AI failure notes
  productImageUrl?: string; // Added for guest uploads
  contactEmail?: string; // Added for guests
  contactPhone?: string; // Added for guests
  contactTelegram?: string; // Added for guests
}