


import { ProductionFacility, ProductItem, UserRole, Inquiry, SearchCriteria, User, Employee, WorkLogEntry, ArchivedEmployee, ArchivedWorkLogEntry, DelegationRequest, SpecialOffer, SpecialOfferViewLog, TurnkeyProject, ProjectStage } from '../types';
import { PRODUCT_CATEGORIES_OPTIONS } from '../constants';
import { notificationService } from './notificationService'; 
import { GoogleGenAI } from "@google/genai";
import { supabase } from './supabaseClient';
import { cacheService } from './cacheService';

const SUPABASE_INIT_ERROR = "Supabase client is not initialized. Please check your VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables in your Vercel project settings.";

// --- Data Mapping Helpers ---
const mapDbProductToApp = (p: any): ProductItem => ({
  id: p.id,
  name: p.name,
  description: p.description,
  estimatedProductionTime: p.estimated_production_time,
  materials: p.materials || [],
  capacityPerWeek: p.capacity_per_week || undefined,
});

const mapDbFacilityToApp = (f: any): Omit<ProductionFacility, 'products'> => ({
  id: f.id,
  ownerId: f.owner_id,
  name: f.name,
  location: f.location,
  city: f.city,
  contactInfo: f.contact_info,
  productionLoad: f.production_load,
  productCategories: f.product_categories || [],
  estimatedTravelTime: f.estimated_travel_time || undefined,
  generalTurnaroundTime: f.general_turnaround_time || undefined,
  certifications: f.certifications || [],
  images: f.images || [],
});

const mapDbInquiryToApp = (i: any): Inquiry => ({
  id: i.id,
  clientId: i.client_id,
  clientName: i.client_name,
  productionFacilityId: i.production_facility_id,
  productionFacilityName: i.production_facility_name,
  message: i.message,
  timestamp: new Date(i.timestamp),
  status: i.status,
  response: i.response || undefined,
  isAutoGenerated: !!i.is_auto_generated,
  originalDelegationRequestId: i.original_delegation_request_id || undefined,
  turnkeyProjectId: i.turnkey_project_id || undefined,
});

// --- API Service Object ---
interface SubmitInquiryData {
  clientId: string;
  clientName: string;
  productionFacilityId: string;
  productionFacilityName: string;
  message: string;
  isAutoGenerated?: boolean;
  originalDelegationRequestId?: string;
  turnkeyProjectId?: string;
}

interface AddProductData extends Omit<ProductItem, 'id'> {}

interface AddEmployeeData extends Omit<Employee, 'id' | 'facilityOwnerId'> {}
interface UpdateEmployeeData extends Partial<AddEmployeeData> {}
interface AddWorkLogData extends Omit<WorkLogEntry, 'id' | 'facilityOwnerId' | 'calculatedPay' | 'createdAt'> {}

interface SubmitDelegationData {
    clientId?: string;
    clientName: string;
    searchCriteria: SearchCriteria;
    contactEmail?: string;
    contactPhone?: string;
    contactTelegram?: string;
}

interface CreateSpecialOfferData extends Omit<SpecialOffer, 'id' | 'createdAt' | 'updatedAt' | 'viewCount'> {}

interface CreateTurnkeyProjectData extends Omit<TurnkeyProject, 'id' | 'createdAt' | 'status' | 'stages' | 'adminNotes'> {}


export const apiService = {
  // --- Production Facilities ---
  getProductionFacilities: async (criteria: Partial<SearchCriteria> = {}): Promise<ProductionFacility[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `facilities:${JSON.stringify(criteria)}`;
    const cached = cacheService.get<ProductionFacility[]>(cacheKey);
    if (cached) return cached;
    
    let query = supabase.from('production_facilities').select(`*`);

    if (criteria.query) {
      const q = `%${criteria.query.toLowerCase()}%`;
      query = query.or(`name.ilike.${q},city.ilike.${q}`);
    }
    if (criteria.productCategory) {
      query = query.contains('product_categories', [criteria.productCategory]);
    }
    if (criteria.minLoad !== undefined) {
      query = query.gte('production_load', criteria.minLoad);
    }
    if (criteria.maxLoad !== undefined) {
      query = query.lte('production_load', criteria.maxLoad);
    }
    if (criteria.certifications && criteria.certifications.length > 0) {
      query = query.contains('certifications', criteria.certifications);
    }
    
    const { data: facilitiesData, error } = await query;
    if (error) {
        console.error("Error fetching facilities:", error);
        throw error;
    }
    if (!facilitiesData || facilitiesData.length === 0) return [];
    
    const facilityIds = facilitiesData.map(f => f.id);
    const { data: productsData, error: productsError } = await supabase.from('products').select('*').in('facility_id', facilityIds);
    if(productsError) throw productsError;

    const productsByFacilityId = (productsData || []).reduce((acc, product) => {
        if(!acc[product.facility_id]) acc[product.facility_id] = [];
        acc[product.facility_id].push(mapDbProductToApp(product));
        return acc;
    }, {} as Record<string, ProductItem[]>);
    
    const result = facilitiesData.map(facility => ({
        ...mapDbFacilityToApp(facility),
        products: productsByFacilityId[facility.id] || []
    }));
    
    cacheService.set(cacheKey, result);
    return result;
  },

  getProductionFacilityById: async (id: string): Promise<ProductionFacility | undefined> => {
     if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
     const cacheKey = `facilities:id:${id}`;
     const cached = cacheService.get<ProductionFacility>(cacheKey);
     if (cached) return cached;

     const { data: facilityData, error } = await supabase.from('production_facilities').select(`*`).eq('id', id).single();
     if (error) {
        console.error(`Error fetching facility ${id}:`, error);
        if (error.code === 'PGRST116') return undefined; // Not found
        throw error;
     }

     const { data: productsData, error: productsError } = await supabase.from('products').select('*').eq('facility_id', id);
     if(productsError) throw productsError;

     const result: ProductionFacility = {
        ...mapDbFacilityToApp(facilityData),
        products: (productsData || []).map(mapDbProductToApp)
     };

     cacheService.set(cacheKey, result);
     return result;
  },

  getProductionFacilityByOwnerId: async (ownerId: string): Promise<ProductionFacility | undefined> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `facilities:owner:${ownerId}`;
    const cached = cacheService.get<ProductionFacility>(cacheKey);
    if (cached) return cached;

    const { data: facilityData, error } = await supabase.from('production_facilities').select(`*`).eq('owner_id', ownerId).maybeSingle();
    if (error) {
        console.error(`Error fetching facility for owner ${ownerId}:`, error);
        throw error;
    }
    if (!facilityData) return undefined;

    const { data: productsData, error: productsError } = await supabase.from('products').select('*').eq('facility_id', facilityData.id);
    if(productsError) throw productsError;
    
    const result: ProductionFacility = {
        ...mapDbFacilityToApp(facilityData),
        products: (productsData || []).map(mapDbProductToApp)
    };
    cacheService.set(cacheKey, result);
    return result;
  },

  updateProductionFacility: async (updatedFacility: ProductionFacility): Promise<ProductionFacility> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    
    const { products, ownerId, productionLoad, productCategories, contactInfo, estimatedTravelTime, generalTurnaroundTime, ...rest } = updatedFacility;
    
    const facilityDataForUpdate = {
        ...rest,
        owner_id: ownerId,
        production_load: productionLoad,
        product_categories: productCategories,
        contact_info: contactInfo,
        estimated_travel_time: estimatedTravelTime,
        general_turnaround_time: generalTurnaroundTime
    };

    const { data, error } = await supabase
        .from('production_facilities')
        .update(facilityDataForUpdate)
        .eq('id', updatedFacility.id)
        .select()
        .single();

    if (error) throw error;
    
    cacheService.invalidate('facilities');
    notificationService.addNotification('admin1', `Производство "${updatedFacility.name}" обновило свои данные.`, 'facility_updated', undefined, updatedFacility.name);
    return {
        ...mapDbFacilityToApp(data),
        products: products 
    };
  },

  ensureManufacturerFacility: async (userId: string, userName: string): Promise<ProductionFacility> => {
      if (!supabase) {
        console.warn("Supabase not connected, returning mock facility");
        // Return a mock facility when Supabase is not available
        return {
          id: `facility-${userId}`,
          ownerId: userId,
          name: `${userName} Manufacturing`,
          location: 'Адрес не указан',
          city: 'Город не указан',
          contactInfo: 'Контакты не указаны',
          productionLoad: 0,
          productCategories: [],
          products: [],
          images: [],
          certifications: [],
        };
      }
      
      let facility = await apiService.getProductionFacilityByOwnerId(userId);
      if (facility) return facility;

      const newFacilityData = {
          id: `facility-${userId}`,
          owner_id: userId,
          name: `${userName} Manufacturing`,
          location: 'Адрес не указан',
          city: 'Город не указан',
          contact_info: 'Контакты не указаны',
          production_load: 0,
          product_categories: [] as string[],
          images: [] as string[],
          certifications: [] as string[],
      };
      
      const { data, error } = await supabase.from('production_facilities').insert(newFacilityData).select().single();
      if (error) throw error;

      facility = { 
          ...mapDbFacilityToApp(data), 
          products: [] 
      };
      cacheService.invalidate('facilities');
      return facility;
  },

  // --- Products in Facility ---
  addProductToFacility: async (facilityId: string, productData: AddProductData): Promise<ProductItem> => {
     if (!supabase) throw new Error(SUPABASE_INIT_ERROR);

     const { estimatedProductionTime, capacityPerWeek, ...rest } = productData;
     const productDataForInsert = {
        ...rest,
        estimated_production_time: estimatedProductionTime,
        capacity_per_week: capacityPerWeek,
        facility_id: facilityId,
        id: `prod-${Date.now()}`
     };

    const { data, error } = await supabase
        .from('products')
        .insert(productDataForInsert)
        .select()
        .single();
    if (error) throw error;
    cacheService.invalidate('facilities');
    return mapDbProductToApp(data);
  },

  updateProductInFacility: async (facilityId: string, updatedProduct: ProductItem): Promise<ProductItem> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    
    const { id, estimatedProductionTime, capacityPerWeek, ...rest } = updatedProduct;
    const productDataForUpdate = {
        ...rest,
        estimated_production_time: estimatedProductionTime,
        capacity_per_week: capacityPerWeek
    };

    const { data, error } = await supabase
        .from('products')
        .update(productDataForUpdate)
        .eq('id', id)
        .eq('facility_id', facilityId)
        .select()
        .single();
    if (error) throw error;
    cacheService.invalidate('facilities');
    return mapDbProductToApp(data);
  },

  deleteProductFromFacility: async (facilityId: string, productId: string): Promise<void> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);

    const { error } = await supabase.from('products').delete().eq('id', productId).eq('facility_id', facilityId);
    if (error) throw error;
    cacheService.invalidate('facilities');
  },

  // --- Inquiries ---
  submitInquiry: async (inquiryData: SubmitInquiryData): Promise<Inquiry> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    
    const { clientId, clientName, productionFacilityId, productionFacilityName, isAutoGenerated, originalDelegationRequestId, turnkeyProjectId, ...rest } = inquiryData;
    const inquiryDataForInsert = {
        ...rest,
        client_id: clientId,
        client_name: clientName,
        production_facility_id: productionFacilityId,
        production_facility_name: productionFacilityName,
        is_auto_generated: isAutoGenerated,
        original_delegation_request_id: originalDelegationRequestId,
        turnkey_project_id: turnkeyProjectId,
        id: `inq-${Date.now()}`, 
        status: 'New' as const
    };

     const { data: newInquiry, error } = await supabase
        .from('inquiries')
        .insert(inquiryDataForInsert)
        .select()
        .single();
    if (error) throw error;

    cacheService.invalidate('inquiries');
    if (inquiryData.turnkeyProjectId) {
        cacheService.invalidate('turnkey');
    }

    const facility = await apiService.getProductionFacilityById(inquiryData.productionFacilityId);
    if (facility) {
         notificationService.addNotification(facility.ownerId, `Получен новый запрос от клиента ${inquiryData.clientName}`, 'new_inquiry', newInquiry.id, inquiryData.clientName);
    }
    notificationService.addNotification('admin1', `Клиент ${inquiryData.clientName} отправил запрос в ${inquiryData.productionFacilityName}`, 'new_inquiry', newInquiry.id, inquiryData.clientName);

    return mapDbInquiryToApp(newInquiry);
  },

  getInquiriesByClient: async (clientId: string): Promise<Inquiry[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `inquiries:client:${clientId}`;
    const cached = cacheService.get<Inquiry[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('inquiries').select('*').eq('client_id', clientId).order('timestamp', { ascending: false });
    if(error) throw error;
    
    const result = (data || []).map(mapDbInquiryToApp);
    cacheService.set(cacheKey, result);
    return result;
  },

  getInquiriesForFacility: async (facilityId: string): Promise<Inquiry[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `inquiries:facility:${facilityId}`;
    const cached = cacheService.get<Inquiry[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('inquiries').select('*').eq('production_facility_id', facilityId).order('timestamp', { ascending: false });
    if(error) throw error;
    const result = (data || []).map(mapDbInquiryToApp);
    cacheService.set(cacheKey, result);
    return result;
  },

  getAllInquiries: async (): Promise<Inquiry[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `inquiries:all`;
    const cached = cacheService.get<Inquiry[]>(cacheKey);
    if (cached) return cached;
    
    const { data, error } = await supabase.from('inquiries').select('*').order('timestamp', { ascending: false });
    if(error) throw error;
    const result = (data || []).map(mapDbInquiryToApp);
    cacheService.set(cacheKey, result);
    return result;
  },

  updateInquiryStatus: async (inquiryId: string, status: Inquiry['status'], responseText?: string): Promise<Inquiry> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);

    const updateData: { status: Inquiry['status']; response?: string } = { status };
    if (responseText !== undefined) {
        updateData.response = responseText;
    }

    const { data: inquiry, error } = await supabase.from('inquiries').update(updateData).eq('id', inquiryId).select().single();
    if (error) throw error;
    
    cacheService.invalidate('inquiries');

    if (responseText && status === 'Responded') {
        notificationService.addNotification(inquiry.client_id, `Производство "${inquiry.production_facility_name}" ответило на ваш запрос.`, 'inquiry_response', inquiryId, inquiry.production_facility_name);
    }
    return mapDbInquiryToApp(inquiry);
  },
  
  // --- User Management (Admin) ---
  getAllUsers: async (): Promise<User[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `users:all`;
    const cached = cacheService.get<User[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('users').select('*');
    if (error) throw error;

    const result = (data || []).map(u => ({
        id: u.id,
        name: u.name,
        role: u.role,
        isActive: u.is_active || false,
    }));
    
    cacheService.set(cacheKey, result);
    return result;
  },

  updateUser: async (userId: string, updates: Partial<User>): Promise<User> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { isActive, ...rest } = updates;
    const updateData: { [key: string]: any } = { ...rest };
    if (isActive !== undefined) {
        updateData.is_active = isActive;
    }

    const { data, error } = await supabase.from('users').update(updateData).eq('id', userId).select().single();
    if(error) throw error;
    cacheService.invalidate('users');
    return {
        id: data.id,
        name: data.name,
        role: data.role,
        isActive: data.is_active || false,
    };
  },

  // --- Employees & Work Logs ---
  getEmployeesByFacilityOwner: async (ownerId: string): Promise<Employee[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `employees:owner:${ownerId}`;
    const cached = cacheService.get<Employee[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('employees').select('*').eq('facility_owner_id', ownerId);
    if(error) throw error;
    
    const result = (data || []).map(e => ({
        id: e.id,
        facilityOwnerId: e.facility_owner_id,
        name: e.name,
        defaultHourlyRate: e.default_hourly_rate,
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  addEmployee: async (facilityOwnerId: string, employeeData: AddEmployeeData): Promise<Employee> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { defaultHourlyRate, ...rest } = employeeData;
    const insertData = { ...rest, facility_owner_id: facilityOwnerId, id: `emp-${Date.now()}`, default_hourly_rate: defaultHourlyRate };
    const { data, error } = await supabase.from('employees').insert(insertData).select().single();
    if(error) throw error;
    cacheService.invalidate('employees');
    return {
        id: data.id,
        facilityOwnerId: data.facility_owner_id,
        name: data.name,
        defaultHourlyRate: data.default_hourly_rate,
    };
  },
  updateEmployee: async (employeeId: string, updates: UpdateEmployeeData): Promise<Employee> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { defaultHourlyRate, ...rest } = updates;
    const updateData: {[key: string]: any} = {...rest};
    if (defaultHourlyRate !== undefined) {
        updateData.default_hourly_rate = defaultHourlyRate;
    }

    const { data, error } = await supabase.from('employees').update(updateData).eq('id', employeeId).select().single();
    if(error) throw error;
    cacheService.invalidate('employees');
    return {
        id: data.id,
        facilityOwnerId: data.facility_owner_id,
        name: data.name,
        defaultHourlyRate: data.default_hourly_rate,
    };
  },
  deleteEmployee: async (employeeId: string): Promise<void> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);

    const { data: employee, error: getError } = await supabase.from('employees').select('*').eq('id', employeeId).single();
    if (getError || !employee) throw new Error("Employee not found.");

    const { error: archiveError } = await supabase.from('archived_employees').insert({ ...employee, archived_at: new Date().toISOString() });
    if (archiveError) throw archiveError;

    const { error: deleteError } = await supabase.from('employees').delete().eq('id', employeeId);
    if (deleteError) throw deleteError;

    cacheService.invalidate('employees');
    cacheService.invalidate('archive');
  },

  getWorkLogEntriesByFacilityOwner: async (ownerId: string): Promise<WorkLogEntry[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `worklogs:owner:${ownerId}`;
    const cached = cacheService.get<WorkLogEntry[]>(cacheKey);
    if (cached) return cached;
    
    const { data, error } = await supabase.from('work_log_entries').select('*').eq('facility_owner_id', ownerId).order('date', {ascending: false});
    if(error) throw error;
    const result = (data || []).map(e => ({
        id: e.id,
        facilityOwnerId: e.facility_owner_id,
        employeeId: e.employee_id,
        employeeName: e.employee_name,
        date: e.date,
        hoursWorked: e.hours_worked,
        hourlyRate: e.hourly_rate,
        calculatedPay: e.calculated_pay,
        workDescription: e.work_description || undefined,
        createdAt: new Date(e.created_at),
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  addWorkLogEntry: async (facilityOwnerId: string, workLogData: AddWorkLogData): Promise<WorkLogEntry> => {
      if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
      const { hoursWorked, hourlyRate, employeeId, employeeName, workDescription, ...rest } = workLogData;
      const newEntryData = {
          ...rest,
          id: `log-${Date.now()}`,
          facility_owner_id: facilityOwnerId,
          employee_id: employeeId,
          employee_name: employeeName,
          hours_worked: hoursWorked,
          hourly_rate: hourlyRate,
          calculated_pay: hoursWorked * hourlyRate,
          work_description: workDescription,
          created_at: new Date().toISOString(),
      };
      const { data, error } = await supabase.from('work_log_entries').insert(newEntryData).select().single();
      if(error) throw error;
      cacheService.invalidate('worklogs');
      return {
        id: data.id,
        facilityOwnerId: data.facility_owner_id,
        employeeId: data.employee_id,
        employeeName: data.employee_name,
        date: data.date,
        hoursWorked: data.hours_worked,
        hourlyRate: data.hourly_rate,
        calculatedPay: data.calculated_pay,
        workDescription: data.work_description || undefined,
        createdAt: new Date(data.created_at),
    };
  },
  updateWorkLogEntry: async (entryId: string, updates: Partial<WorkLogEntry>): Promise<WorkLogEntry> => {
       if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
       const entryToUpdate: {[key: string]: any} = {};
       if(updates.date) entryToUpdate.date = updates.date;
       if(updates.hoursWorked) entryToUpdate.hours_worked = updates.hoursWorked;
       if(updates.hourlyRate) entryToUpdate.hourly_rate = updates.hourlyRate;
       if(updates.workDescription) entryToUpdate.work_description = updates.workDescription;
       
       if(updates.hoursWorked || updates.hourlyRate){
           const { data: currentEntry } = await supabase.from('work_log_entries').select('hours_worked, hourly_rate').eq('id', entryId).single();
           if(currentEntry){
               const hours = updates.hoursWorked ?? currentEntry.hours_worked;
               const rate = updates.hourlyRate ?? currentEntry.hourly_rate;
               entryToUpdate.calculated_pay = hours * rate;
           }
       }
       const { data, error } = await supabase.from('work_log_entries').update(entryToUpdate).eq('id', entryId).select().single();
       if(error) throw error;
       cacheService.invalidate('worklogs');
       return {
            id: data.id,
            facilityOwnerId: data.facility_owner_id,
            employeeId: data.employee_id,
            employeeName: data.employee_name,
            date: data.date,
            hoursWorked: data.hours_worked,
            hourlyRate: data.hourly_rate,
            calculatedPay: data.calculated_pay,
            workDescription: data.work_description || undefined,
            createdAt: new Date(data.created_at),
       };
  },
  deleteWorkLogEntry: async (entryId: string): Promise<void> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { data: entry, error: getError } = await supabase.from('work_log_entries').select('*').eq('id', entryId).single();
    if (getError || !entry) throw new Error("Work log entry not found.");

    const { error: archiveError } = await supabase.from('archived_work_log_entries').insert({ ...entry, archived_at: new Date().toISOString() });
    if (archiveError) throw archiveError;
    
    const { error: deleteError } = await supabase.from('work_log_entries').delete().eq('id', entryId);
    if (deleteError) throw deleteError;
    cacheService.invalidate('worklogs');
    cacheService.invalidate('archive');
  },
  getArchivedEmployeesByFacilityOwner: async (ownerId: string): Promise<ArchivedEmployee[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `archive:employees:${ownerId}`;
    const cached = cacheService.get<ArchivedEmployee[]>(cacheKey);
    if(cached) return cached;
    
    const { data, error } = await supabase.from('archived_employees').select('*').eq('facility_owner_id', ownerId);
    if(error) throw error;
    const result = (data || []).map(e => ({
        id: e.id,
        facilityOwnerId: e.facility_owner_id,
        name: e.name,
        defaultHourlyRate: e.default_hourly_rate,
        archivedAt: new Date(e.archived_at)
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  getArchivedWorkLogEntriesByFacilityOwner: async (ownerId: string): Promise<ArchivedWorkLogEntry[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `archive:worklogs:${ownerId}`;
    const cached = cacheService.get<ArchivedWorkLogEntry[]>(cacheKey);
    if(cached) return cached;

    const { data, error } = await supabase.from('archived_work_log_entries').select('*').eq('facility_owner_id', ownerId);
    if(error) throw error;
    const result = (data || []).map(e => ({
        id: e.id,
        facilityOwnerId: e.facility_owner_id,
        employeeId: e.employee_id,
        employeeName: e.employee_name,
        date: e.date,
        hoursWorked: e.hours_worked,
        hourlyRate: e.hourly_rate,
        calculatedPay: e.calculated_pay,
        workDescription: e.work_description || undefined,
        createdAt: new Date(e.created_at),
        archivedAt: new Date(e.archived_at)
    }));
    cacheService.set(cacheKey, result);
    return result;
  },

  // --- Delegation Requests ---
  submitDelegationRequest: async (delegationData: SubmitDelegationData): Promise<DelegationRequest> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { clientId, clientName, searchCriteria, contactEmail, contactPhone, contactTelegram } = delegationData;
    const newRequestData = {
        id: `deleg-${Date.now()}`,
        client_id: clientId,
        client_name: clientName,
        search_criteria: searchCriteria,
        contact_email: contactEmail,
        contact_phone: contactPhone,
        contact_telegram: contactTelegram,
        timestamp: new Date().toISOString(),
        status: 'Новая' as const,
    };
    
    const { data: insertedData, error } = await supabase.from('delegation_requests').insert(newRequestData).select().single();
    if (error) throw error;

    cacheService.invalidate('delegations');
    notificationService.addNotification('admin1', `Получена новая заявка на подбор от клиента ${newRequestData.client_name}`, 'new_delegation_request', newRequestData.id, newRequestData.client_name);
    if (newRequestData.client_id) {
        notificationService.addNotification(newRequestData.client_id, 'Ваша заявка на подбор отправлена администратору.', 'delegation_request_update', newRequestData.id, 'Заявка на подбор');
    }
    return {
        ...insertedData,
        clientId: insertedData.client_id || undefined,
        clientName: insertedData.client_name,
        searchCriteria: insertedData.search_criteria as SearchCriteria,
        adminNotes: insertedData.admin_notes || undefined,
        contactEmail: insertedData.contact_email || undefined,
        contactPhone: insertedData.contact_phone || undefined,
        contactTelegram: insertedData.contact_telegram || undefined,
        timestamp: new Date(insertedData.timestamp)
    } as DelegationRequest;
  },
  getDelegationRequests: async (): Promise<DelegationRequest[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `delegations:all`;
    const cached = cacheService.get<DelegationRequest[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('delegation_requests').select('*').order('timestamp', { ascending: false });
    if(error) throw error;
    const result = (data || []).map(d => ({
        id: d.id,
        clientId: d.client_id || undefined,
        clientName: d.client_name,
        searchCriteria: d.search_criteria as SearchCriteria,
        timestamp: new Date(d.timestamp),
        status: d.status,
        adminNotes: d.admin_notes || undefined,
        contactEmail: d.contact_email || undefined,
        contactPhone: d.contact_phone || undefined,
        contactTelegram: d.contact_telegram || undefined,
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  updateDelegationRequestStatus: async (requestId: string, status: DelegationRequest['status'], adminNotes?: string): Promise<DelegationRequest> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const updateData: {[key: string]: any} = { status };
    if (adminNotes !== undefined) {
        updateData.admin_notes = adminNotes;
    }
    const { data: request, error } = await supabase.from('delegation_requests').update(updateData).eq('id', requestId).select().single();
    if(error) throw error;
    
    cacheService.invalidate('delegations');
    if (request.client_id) {
        notificationService.addNotification(request.client_id, `Статус вашей заявки на подбор #${request.id.slice(-6)} обновлен: ${status}.`, 'delegation_request_update', request.id);
    }
    return {
        id: request.id,
        clientId: request.client_id || undefined,
        clientName: request.client_name,
        searchCriteria: request.search_criteria as SearchCriteria,
        timestamp: new Date(request.timestamp),
        status: request.status,
        adminNotes: request.admin_notes || undefined,
        contactEmail: request.contact_email || undefined,
        contactPhone: request.contact_phone || undefined,
        contactTelegram: request.contact_telegram || undefined,
    };
  },
  sendAutomatedInquiriesForDelegation: async (request: DelegationRequest, facilities: ProductionFacility[], admin: User): Promise<{ inquiriesSentCount: number }> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    let count = 0;
    const inquiriesToCreate = [];
    for (const facility of facilities) {
        const message = `Уважаемый партнер! Администратор платформы "${admin.name}" подобрал ваше производство для выполнения заказа от клиента "${request.clientName}".\n\nКритерии поиска:\n- Запрос: ${request.searchCriteria.query}\n- Категория: ${request.searchCriteria.productCategory || 'Не указана'}\n\nПожалуйста, рассмотрите данный запрос.`;
        count++;
        inquiriesToCreate.push({
            client_id: request.clientId!,
            client_name: request.clientName,
            production_facility_id: facility.id,
            production_facility_name: facility.name,
            message: message,
            status: 'New' as const,
            is_auto_generated: true,
            original_delegation_request_id: request.id,
        });
    }
    
    if (inquiriesToCreate.length > 0) {
        const { data: insertedInquiries, error: insertError } = await supabase.from('inquiries').insert(inquiriesToCreate).select();
        if(insertError) throw insertError;
        
        cacheService.invalidate('inquiries');
        (insertedInquiries || []).forEach(inq => {
             const facility = facilities.find(f => f.id === inq.production_facility_id)!;
             notificationService.addNotification(facility.ownerId, `Новый автоматический запрос от клиента ${inq.client_name} (подобран администратором)`, 'admin_initiated_match_inquiry', inq.id, inq.client_name);
        });
    }
    
    await apiService.updateDelegationRequestStatus(request.id, 'Предложения отправлены', (request.adminNotes || '') + `\n[Авто] Отправлено запросов: ${count} (${new Date().toLocaleString()})`);
    cacheService.invalidate('delegations');

    if (request.clientId) {
        notificationService.addNotification(request.clientId, `Администратор подобрал ${count} производств по вашей заявке #${request.id.slice(-6)}. Ожидайте их ответов.`, 'delegation_request_update', request.id);
    }
    return { inquiriesSentCount: count };
  },

  // --- Special Offers ---
  getSpecialOffers: async (filters: { facilityOwnerId?: string, activeOnly?: boolean }): Promise<SpecialOffer[]> => {
    if (!supabase) {
        console.error("Failed to fetch special offers", SUPABASE_INIT_ERROR);
        throw new Error("Failed to fetch special offers");
    }
    const cacheKey = `offers:${JSON.stringify(filters)}`;
    const cached = cacheService.get<SpecialOffer[]>(cacheKey);
    if (cached) return cached;
    
    let query = supabase.from('special_offers').select('*');
    if (filters.facilityOwnerId) {
        query = query.eq('facility_owner_id', filters.facilityOwnerId);
    }
    if (filters.activeOnly) {
        const today = new Date().toISOString().split('T')[0];
        query = query.eq('is_active', true).gte('valid_until', today);
    }
    const { data, error } = await query.order('created_at', { ascending: false });
    if (error) {
        console.error("Failed to fetch special offers", error);
        throw new Error(`Failed to fetch special offers`);
    }
    
    const result = (data || []).map(o => ({
        id: o.id,
        facilityId: o.facility_id,
        facilityOwnerId: o.facility_owner_id,
        facilityName: o.facility_name,
        title: o.title,
        description: o.description,
        discountPercentage: o.discount_percentage || undefined,
        fixedDiscountAmount: o.fixed_discount_amount || undefined,
        applicableServices: o.applicable_services || [],
        validFrom: o.valid_from,
        validUntil: o.valid_until,
        promoCode: o.promo_code || undefined,
        termsAndConditions: o.terms_and_conditions || undefined,
        imageUrl: o.image_url || undefined,
        createdAt: new Date(o.created_at),
        updatedAt: new Date(o.updated_at),
        isActive: o.is_active,
        viewCount: o.view_count,
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  createSpecialOffer: async (offerData: CreateSpecialOfferData): Promise<SpecialOffer> => {
      if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
      const { facilityId, facilityOwnerId, facilityName, discountPercentage, fixedDiscountAmount, applicableServices, validFrom, validUntil, promoCode, termsAndConditions, imageUrl, isActive, ...rest } = offerData;
      const newOfferData = {
          ...rest,
          id: `offer-${Date.now()}`,
          facility_id: facilityId,
          facility_owner_id: facilityOwnerId,
          facility_name: facilityName,
          discount_percentage: discountPercentage,
          fixed_discount_amount: fixedDiscountAmount,
          applicable_services: applicableServices,
          valid_from: validFrom,
          valid_until: validUntil,
          promo_code: promoCode,
          terms_and_conditions: termsAndConditions,
          image_url: imageUrl,
          is_active: isActive,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          view_count: 0
      };

      const { data, error } = await supabase.from('special_offers').insert(newOfferData).select().single();
      if (error) throw error;

      cacheService.invalidate('offers');
      return {
          id: data.id,
          facilityId: data.facility_id,
          facilityOwnerId: data.facility_owner_id,
          facilityName: data.facility_name,
          title: data.title,
          description: data.description,
          discountPercentage: data.discount_percentage || undefined,
          fixedDiscountAmount: data.fixed_discount_amount || undefined,
          applicableServices: data.applicable_services || [],
          validFrom: data.valid_from,
          validUntil: data.valid_until,
          promoCode: data.promo_code || undefined,
          termsAndConditions: data.terms_and_conditions || undefined,
          imageUrl: data.image_url || undefined,
          createdAt: new Date(data.created_at),
          updatedAt: new Date(data.updated_at),
          isActive: data.is_active,
          viewCount: data.view_count,
      };
  },
  updateSpecialOffer: async (offerId: string, updates: Partial<CreateSpecialOfferData>): Promise<SpecialOffer> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    
    const { facilityId, facilityOwnerId, facilityName, discountPercentage, fixedDiscountAmount, applicableServices, validFrom, validUntil, promoCode, termsAndConditions, imageUrl, isActive, ...rest } = updates;
    const updateData: {[key: string]: any} = {
        ...rest,
        updated_at: new Date().toISOString()
    };
    if (facilityId !== undefined) updateData.facility_id = facilityId;
    if (facilityOwnerId !== undefined) updateData.facility_owner_id = facilityOwnerId;
    if (facilityName !== undefined) updateData.facility_name = facilityName;
    if (discountPercentage !== undefined) updateData.discount_percentage = discountPercentage;
    if (fixedDiscountAmount !== undefined) updateData.fixed_discount_amount = fixedDiscountAmount;
    if (applicableServices !== undefined) updateData.applicable_services = applicableServices;
    if (validFrom !== undefined) updateData.valid_from = validFrom;
    if (validUntil !== undefined) updateData.valid_until = validUntil;
    if (promoCode !== undefined) updateData.promo_code = promoCode;
    if (termsAndConditions !== undefined) updateData.terms_and_conditions = termsAndConditions;
    if (imageUrl !== undefined) updateData.image_url = imageUrl;
    if (isActive !== undefined) updateData.is_active = isActive;
    
    const { data, error } = await supabase.from('special_offers').update(updateData).eq('id', offerId).select().single();
    if (error) throw error;
    cacheService.invalidate('offers');
    return {
        id: data.id,
        facilityId: data.facility_id,
        facilityOwnerId: data.facility_owner_id,
        facilityName: data.facility_name,
        title: data.title,
        description: data.description,
        discountPercentage: data.discount_percentage || undefined,
        fixedDiscountAmount: data.fixed_discount_amount || undefined,
        applicableServices: data.applicable_services || [],
        validFrom: data.valid_from,
        validUntil: data.valid_until,
        promoCode: data.promo_code || undefined,
        termsAndConditions: data.terms_and_conditions || undefined,
        imageUrl: data.image_url || undefined,
        createdAt: new Date(data.created_at),
        updatedAt: new Date(data.updated_at),
        isActive: data.is_active,
        viewCount: data.view_count,
    }
  },
  deleteSpecialOffer: async (offerId: string): Promise<void> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { error } = await supabase.from('special_offers').delete().eq('id', offerId);
    if(error) throw error;
    cacheService.invalidate('offers');
  },
  recordSpecialOfferView: async (offerId: string, clientId: string, clientName: string): Promise<void> => {
      if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
      
      const { data: remoteExistingLog } = await supabase.from('special_offer_view_logs').select('id').eq('offer_id', offerId).eq('client_id', clientId).maybeSingle();
      if (!remoteExistingLog) {
          await supabase.rpc('increment_offer_view', { offer_id_in: offerId });
          await supabase.from('special_offer_view_logs').insert({ offer_id: offerId, client_id: clientId, client_name: clientName, follow_up_sent: false });
          cacheService.invalidate('offers');
          const {data: offer} = await supabase.from('special_offers').select('title, facility_owner_id').eq('id', offerId).single();
          if (offer) {
              notificationService.addNotification(offer.facility_owner_id, `Клиент "${clientName}" просмотрел ваше спецпредложение "${offer.title}".`, 'new_special_offer_viewed', offerId, clientName);
          }
      }
  },
  getSpecialOfferViewLogs: async (offerId: string): Promise<SpecialOfferViewLog[]> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const cacheKey = `offers:logs:${offerId}`;
    const cached = cacheService.get<SpecialOfferViewLog[]>(cacheKey);
    if (cached) return cached;

    const { data, error } = await supabase.from('special_offer_view_logs').select('*').eq('offer_id', offerId).order('viewed_at', { ascending: false });
    if (error) throw error;
    
    const result = (data || []).map(l => ({
        id: l.id,
        offerId: l.offer_id,
        clientId: l.client_id,
        clientName: l.client_name,
        viewedAt: new Date(l.viewed_at),
        followUpSent: l.follow_up_sent,
        followUpMessage: l.follow_up_message || undefined,
    }));
    cacheService.set(cacheKey, result);
    return result;
  },
  sendFollowUpToOfferViewer: async (viewLogId: string, message: string): Promise<SpecialOfferViewLog> => {
    if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
    const { data: viewLog, error } = await supabase.from('special_offer_view_logs').update({ follow_up_sent: true, follow_up_message: message }).eq('id', viewLogId).select().single();
    if(error) throw error;
    
    cacheService.invalidate('offers');
    const { data: offer } = await supabase.from('special_offers').select('id, facility_name').eq('id', viewLog.offer_id).single();
    if (offer) {
      notificationService.addNotification(viewLog.client_id, `Производство "${offer.facility_name}" отправило вам сообщение по спецпредложению.`, 'follow_up_offer_received', offer.id, offer.facility_name);
    }
    return {
        id: viewLog.id,
        offerId: viewLog.offer_id,
        clientId: viewLog.client_id,
        clientName: viewLog.client_name,
        viewedAt: new Date(viewLog.viewed_at),
        followUpSent: viewLog.follow_up_sent,
        followUpMessage: viewLog.follow_up_message || undefined,
    };
  },
  
  // --- Turnkey Projects ---
  createTurnkeyProject: async (projectData: CreateTurnkeyProjectData): Promise<TurnkeyProject> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        const apiKey = process.env.API_KEY;
        const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;
        let generatedStages: ProjectStage[] = [];
        let status: TurnkeyProject['status'] = 'pending_review';
        let adminNotes: string | undefined;

        if (ai) {
          try {
              const prompt = `Based on this product description, break it down into a maximum of 5 logical, sequential manufacturing stages. For each stage, provide a "name", a "description", a single most relevant "requiredCategory" from this list [${PRODUCT_CATEGORIES_OPTIONS.join(', ')}], and an array of "keywords" for finding a contractor. Respond in valid JSON format: [{"stage": 1, "name": "...", "description": "...", "requiredCategory": "...", "keywords": ["...", "..."]}, ...]. Product description: "${projectData.productDescription}"`;
              
              const response = await ai.models.generateContent({ model: 'gemini-2.5-flash', contents: prompt });
              const jsonText = response.text.trim().replace(/```json|```/g, '');
              const parsedStages = JSON.parse(jsonText);
              
              if (Array.isArray(parsedStages)) {
                  generatedStages = parsedStages.map((s, index) => ({ ...s, stage: index + 1, status: 'pending' }));
              } else {
                  throw new Error("AI response was not a JSON array.");
              }
              status = 'pending_review';
          } catch (e: any) {
              console.error("AI stage generation failed:", e);
              status = 'pending_review';
              adminNotes = `AI stage generation failed. Reason: ${e.message || 'Unknown error'}. Please review and create stages manually.`;
          }
        } else {
            status = 'pending_review';
            adminNotes = "API Key for AI is not configured. Stages need to be created manually.";
        }
        
        const { clientId, clientName, productDescription, projectName, productImageUrl, contactEmail, contactPhone, contactTelegram } = projectData;

        const newProjectData = {
            id: `proj-${Date.now()}`,
            client_id: clientId,
            client_name: clientName,
            product_description: productDescription,
            project_name: projectName,
            stages: generatedStages,
            status,
            created_at: new Date().toISOString(),
            admin_notes: adminNotes,
            product_image_url: productImageUrl,
            contact_email: contactEmail,
            contact_phone: contactPhone,
            contact_telegram: contactTelegram
        };
        
        const { data: newProject, error } = await supabase.from('turnkey_projects').insert(newProjectData).select().single();
        if(error) throw error;
        
        cacheService.invalidate('turnkey');
        notificationService.addNotification('admin1', `Создан новый проект "под ключ": "${newProject.project_name}"`, 'turnkey_project_created', newProject.id, newProject.project_name);
        if (newProject.client_id) {
            notificationService.addNotification(newProject.client_id, `Ваш проект "${newProject.project_name}" принят в обработку.`, 'turnkey_project_created', newProject.id, newProject.project_name);
        }
        return {
            id: newProject.id,
            clientId: newProject.client_id || undefined,
            clientName: newProject.client_name,
            productDescription: newProject.product_description,
            projectName: newProject.project_name,
            stages: (newProject.stages as any) || [],
            status: newProject.status,
            createdAt: new Date(newProject.created_at),
            adminNotes: newProject.admin_notes || undefined,
            productImageUrl: newProject.product_image_url || undefined,
            contactEmail: newProject.contact_email || undefined,
            contactPhone: newProject.contact_phone || undefined,
            contactTelegram: newProject.contact_telegram || undefined,
        };
    },

    getTurnkeyProjectsForClient: async (clientId: string): Promise<TurnkeyProject[]> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        const cacheKey = `turnkey:client:${clientId}`;
        const cached = cacheService.get<TurnkeyProject[]>(cacheKey);
        if (cached) return cached;

        const { data, error } = await supabase.from('turnkey_projects').select('*').eq('client_id', clientId).order('created_at', {ascending: false});
        if(error) throw error;

        const result = (data || []).map(p => ({
            id: p.id,
            clientId: p.client_id || undefined,
            clientName: p.client_name,
            productDescription: p.product_description,
            projectName: p.project_name,
            stages: (p.stages as any) || [],
            status: p.status,
            createdAt: new Date(p.created_at),
            adminNotes: p.admin_notes || undefined,
            productImageUrl: p.product_image_url || undefined,
            contactEmail: p.contact_email || undefined,
            contactPhone: p.contact_phone || undefined,
            contactTelegram: p.contact_telegram || undefined,
        }));
        cacheService.set(cacheKey, result);
        return result;
    },

    getAllTurnkeyProjects: async (): Promise<TurnkeyProject[]> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        const cacheKey = `turnkey:all`;
        const cached = cacheService.get<TurnkeyProject[]>(cacheKey);
        if (cached) return cached;

        const { data, error } = await supabase.from('turnkey_projects').select('*').order('created_at', {ascending: false});
        if(error) throw error;
        
        const result = (data || []).map(p => ({
            id: p.id,
            clientId: p.client_id || undefined,
            clientName: p.client_name,
            productDescription: p.product_description,
            projectName: p.project_name,
            stages: (p.stages as any) || [],
            status: p.status,
            createdAt: new Date(p.created_at),
            adminNotes: p.admin_notes || undefined,
            productImageUrl: p.product_image_url || undefined,
            contactEmail: p.contact_email || undefined,
            contactPhone: p.contact_phone || undefined,
            contactTelegram: p.contact_telegram || undefined,
        }));
        cacheService.set(cacheKey, result);
        return result;
    },
    
    getPublishedTurnkeyProjects: async (): Promise<TurnkeyProject[]> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        const cacheKey = `turnkey:published`;
        const cached = cacheService.get<TurnkeyProject[]>(cacheKey);
        if (cached) return cached;

        const { data, error } = await supabase.from('turnkey_projects').select('*').eq('status', 'published').order('created_at', {ascending: false});
        if(error) throw error;
        
        const result = (data || []).map(p => ({
            id: p.id,
            clientId: p.client_id || undefined,
            clientName: p.client_name,
            productDescription: p.product_description,
            projectName: p.project_name,
            stages: (p.stages as any) || [],
            status: p.status,
            createdAt: new Date(p.created_at),
            adminNotes: p.admin_notes || undefined,
            productImageUrl: p.product_image_url || undefined,
            contactEmail: p.contact_email || undefined,
            contactPhone: p.contact_phone || undefined,
            contactTelegram: p.contact_telegram || undefined,
        }));
        cacheService.set(cacheKey, result);
        return result;
    },

    updateTurnkeyProject: async (projectId: string, updates: Partial<Pick<TurnkeyProject, 'status' | 'adminNotes' | 'stages'>>): Promise<TurnkeyProject> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        
        const { adminNotes, ...rest } = updates;
        const updateData: {[key: string]: any} = { ...rest };
        if (adminNotes !== undefined) {
            updateData.admin_notes = adminNotes;
        }

        const { data: project, error } = await supabase.from('turnkey_projects').update(updateData).eq('id', projectId).select().single();
        if(error) throw error;
        
        cacheService.invalidate('turnkey');

        if (project.client_id) {
            let message = `Статус вашего проекта "${project.project_name}" обновлен: ${project.status}.`;
            if (updates.status === 'published') {
                message = `Ваш проект "${project.project_name}" опубликован на бирже и виден производителям.`;
            }
            notificationService.addNotification(project.client_id, message, 'turnkey_project_update', project.id, project.project_name);
        }

        return {
            id: project.id,
            clientId: project.client_id || undefined,
            clientName: project.client_name,
            productDescription: project.product_description,
            projectName: project.project_name,
            stages: (project.stages as any) || [],
            status: project.status,
            createdAt: new Date(project.created_at),
            adminNotes: project.admin_notes || undefined,
            productImageUrl: project.product_image_url || undefined,
            contactEmail: project.contact_email || undefined,
            contactPhone: project.contact_phone || undefined,
            contactTelegram: project.contact_telegram || undefined,
        };
    },

    getTurnkeyProjectById: async (projectId: string): Promise<TurnkeyProject | undefined> => {
        if (!supabase) throw new Error(SUPABASE_INIT_ERROR);
        const cacheKey = `turnkey:id:${projectId}`;
        const cached = cacheService.get<TurnkeyProject>(cacheKey);
        if(cached) return cached;

        const { data, error } = await supabase.from('turnkey_projects').select('*').eq('id', projectId).single();
        if (error) {
            if (error.code === 'PGRST116') return undefined;
            throw error;
        }

        const result = {
            id: data.id,
            clientId: data.client_id || undefined,
            clientName: data.client_name,
            productDescription: data.product_description,
            projectName: data.project_name,
            stages: (data.stages as any) || [],
            status: data.status,
            createdAt: new Date(data.created_at),
            adminNotes: data.admin_notes || undefined,
            productImageUrl: data.product_image_url || undefined,
            contactEmail: data.contact_email || undefined,
            contactPhone: data.contact_phone || undefined,
            contactTelegram: data.contact_telegram || undefined,
        };
        cacheService.set(cacheKey, result);
        return result;
    },
    
    launchTurnkeyProject: async (projectId: string, updatedStages: ProjectStage[]): Promise<TurnkeyProject> => {
        const project = await apiService.getTurnkeyProjectById(projectId);
        if (!project) throw new Error("Project not found");

        const stagesWithInquiryIds: ProjectStage[] = [];

        for (const stage of updatedStages) {
            if (stage.selectedFacilityId && stage.selectedFacilityName && project.clientId) {
                const inquiryData = {
                    clientId: project.clientId,
                    clientName: project.clientName,
                    productionFacilityId: stage.selectedFacilityId,
                    productionFacilityName: stage.selectedFacilityName,
                    message: `Требуется выполнить этап "${stage.name}" для проекта "${project.projectName}".\n\nОписание этапа: ${stage.description}`,
                    isAutoGenerated: true,
                    turnkeyProjectId: projectId,
                };
                const newInquiry = await apiService.submitInquiry(inquiryData);
                stagesWithInquiryIds.push({ ...stage, status: 'in_progress', inquiryId: newInquiry.id });
            } else {
                 stagesWithInquiryIds.push(stage);
            }
        }
        
        const updatedProject = await apiService.updateTurnkeyProject(projectId, {
            status: 'in_progress',
            stages: stagesWithInquiryIds,
        });

        cacheService.invalidate('turnkey');
        cacheService.invalidate('inquiries');

        if(project.clientId){
             notificationService.addNotification(project.clientId, `Ваш проект "${project.projectName}" запущен в работу.`, 'turnkey_project_update', projectId, project.projectName);
        }
       
        return updatedProject;
    },

};